# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter-sets:
        image_edit:
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true

        image_list:
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
                    allow_upscale: true 
                    
        image_view:
            filters:
                thumbnail:
                    size: [500, 500]
                    mode: outbound
                    allow_upscale: true                    
                    